### ISSUE TITLE
I am getting below Error while using this reusable Datatable component.

### ISSUE THREAD

**Issue by ramki9876** [Nisar-99/Salesforce-LWC-Datatable#4]
while data is loaded for the 1st time its showing all the records in a single page instead of 5 records in a page and pagination is not visible for the 1st time data is getting loaded. getting error as well as attached.
![Error](https://github.com/Nisar-99/Salesforce-LWC-Datatable/assets/63507432/4c54144a-34b3-4eb6-b166-d0146ba4f9f1)

**Comment by ramki9876** [comment]
also row selection is not working properly if i select 3rd row in 1st page when i move to next page 3rd row in 2nd page is selected automatically and selection is not retained properly.

**Comment by QuestMajor** [comment]
Make sure the data you are passing does not contain a NULL value, if it does not contain any data then it should be blank "" instead.

Make sure your OwnerName is not passing a NULL value.
