### ISSUE TITLE
Changing Filtered Columns during search returns an error

### ISSUE THREAD

**Issue by QuestMajor** [Nisar-99/Salesforce-LWC-Datatable#5]
When performing search, ideally the data will be filtered based on the current serchTerm, however if the data for each row is empty or not casted to string, it basically throws this error:

> object[key].toLowerCase is not a function

a simple solution would be to add a null checker to the filter and cast the data to string

From:
`filteredItems = this.dataCollection.filter(o => Object.keys(o).some(k => o[k].toLowerCase().includes(searchTerm)));`

`filteredItems = this.dataCollection.filter(result => result[fieldName].toLowerCase().includes(searchTerm));`

To:
`filteredItems = this.dataCollection.filter(o => Object.keys(o).some(k => o[k] && String(o[k]).toLowerCase().includes(searchTerm)));`

`filteredItems = this.dataCollection.filter(result => result[fieldName] && String(result[fieldName]).toLowerCase().includes(searchTerm));`

**Comment by Nisar-99** [comment]
Fixed
